#!/usr/bin/make -f

# HYPE CLI Build System
# Plugin-based architecture build configuration

# Build configuration
BUILD_DIR := build
SRC_DIR := src
CORE_DIR := $(SRC_DIR)/core
PLUGINS_DIR := $(SRC_DIR)/plugins
TEST_DIR := tests

# Target executable
TARGET := $(BUILD_DIR)/hype
INSTALL_DIR := $(HOME)/.local/bin

# Source files
CORE_FILES := $(wildcard $(CORE_DIR)/*.sh)
PLUGIN_FILES := $(wildcard $(PLUGINS_DIR)/*.sh)
MAIN_FILE := $(SRC_DIR)/main.sh

# Shell check configuration
SHELLCHECK_OPTS := -e SC1091 -e SC2034

.PHONY: all build lint clean test install dev-run help

# Default target
all: build

# Build the final executable
build: $(TARGET)

$(TARGET): $(CORE_FILES) $(PLUGIN_FILES) $(MAIN_FILE)
	@mkdir -p $(BUILD_DIR)
	@echo "Building HYPE CLI..."
	@echo "#!/bin/bash" > $(TARGET)
	@echo "" >> $(TARGET)
	@echo "set -euo pipefail" >> $(TARGET)
	@echo "" >> $(TARGET)
	@echo "# Generated by HYPE CLI build system" >> $(TARGET)
	@echo "# Build date: $$(date)" >> $(TARGET)
	@echo "" >> $(TARGET)
	@for file in $(CORE_FILES); do \
		echo "# Source: $$file" >> $(TARGET); \
		tail -n +2 $$file >> $(TARGET); \
		echo "" >> $(TARGET); \
	done
	@for file in $(PLUGIN_FILES); do \
		echo "# Source: $$file" >> $(TARGET); \
		tail -n +2 $$file >> $(TARGET); \
		echo "" >> $(TARGET); \
	done
	@echo "# Source: $(MAIN_FILE)" >> $(TARGET)
	@tail -n +2 $(MAIN_FILE) >> $(TARGET)
	@chmod +x $(TARGET)
	@echo "Build complete: $(TARGET)"


# Lint all shell scripts
lint:
	@echo "Running ShellCheck..."
	@shellcheck $(SHELLCHECK_OPTS) $(SRC_DIR)/hype || true
	@find $(SRC_DIR) -name "*.sh" -exec shellcheck $(SHELLCHECK_OPTS) {} \;
	@shellcheck $(SHELLCHECK_OPTS) install.sh || true

# Clean build artifacts
clean:
	@echo "Cleaning build artifacts..."
	@rm -rf $(BUILD_DIR)
	@echo "Clean complete"

# Run tests
test:
	@echo "Running test suite..."
	@if [ -f $(TEST_DIR)/test-suite.sh ]; then \
		bash $(TEST_DIR)/test-suite.sh; \
	else \
		echo "Test suite not yet implemented"; \
	fi

# Install to local bin directory
install: build
	@echo "Installing HYPE CLI to $(INSTALL_DIR)..."
	@mkdir -p $(INSTALL_DIR)
	@cp $(TARGET) $(INSTALL_DIR)/hype
	@echo "Installation complete"

# Development mode - run without building
dev-run:
	@echo "Running in development mode..."
	@if [ -f $(TARGET) ]; then \
		$(TARGET) $(ARGS); \
	else \
		echo "No build found. Run 'make build' first."; \
		exit 1; \
	fi

# Show help
help:
	@echo "HYPE CLI Build System"
	@echo ""
	@echo "Available targets:"
	@echo "  build     - Build the final executable (default)"
	@echo "  lint      - Run ShellCheck on all scripts"
	@echo "  clean     - Remove build artifacts"
	@echo "  test      - Run test suite"
	@echo "  install   - Install to ~/.local/bin"
	@echo "  dev-run   - Run built executable (use ARGS=... for arguments)"
	@echo "  help      - Show this help"
	@echo ""
	@echo "Examples:"
	@echo "  make build"
	@echo "  make dev-run ARGS='--version'"
	@echo "  make dev-run ARGS='init'"