templates:
  hype-name: "{{ .Environment.Name }}"
  hype-configmap:
    hoge: fuga
  hype-secrets:
    hoge: fuga

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: nginx
    namespace: default
    chart: bitnami/nginx
    version: ~18.2.0
    values:
      - service:
          type: ClusterIP
          ports:
            http: 80
      - replicaCount: 1
      - resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
      - image:
          pullPolicy: IfNotPresent